// Generated by CoffeeScript 1.10.0
var AfterBrunch, fs, mv,
  bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

mv = require("mv");

fs = require('fs');

module.exports = AfterBrunch = (function() {
  AfterBrunch.prototype.brunchPlugin = true;

  function AfterBrunch(config) {
    this.config = config;
    this.onCompile = bind(this.onCompile, this);
  }

  AfterBrunch.prototype.onCompile = function(generatedFiles) {
    var files, path;
    path = this.config.paths["public"];
    files = fs.readdirSync(path);
    return files.forEach(function(file) {
      if (/\.(eot|svg|ttf|woff|woff2)$/.test(file)) {
        return fs.rename(path + "/" + file, path + "/fonts/" + file);
      }
    });
  };

  return AfterBrunch;

})();
